const playlist = [
    {"pc":0, "name": "Clone",                      "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "220099"},
    {"pc":1, "name": "Si algun día todo falla",    "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "FF0000"},
    {"pc":2, "name": "One with the machine",       "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "00FFFF"},
    {"pc":3, "name": "Lullaby",                    "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "FF7700"},
    {"pc":4, "name": "Bad boy",                    "samples": "BadBoy", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor" : "FF0000"},
    {"pc":5, "name": "FOMO",                       "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "8800FF"},
    {"pc":6, "name": "Tantra",                     "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "00FFFF"},
    {"pc":7, "name": "Sex tape",                   "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "4600FF"},
    {"pc":8, "name": "One night",                  "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": "FF0000"},
    {"pc":9, "name": "This body",                  "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "FF00FF"},
    {"pc":10,"name": "Lockdown",                   "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "00FF00"},
    {"pc":11,"name": "No place for us",            "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "FF5500"},
    {"pc":12,"name": "Never let me down",          "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "0000FF"},
    {"pc":13,"name": "The place you'll never see", "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": ""},
    {"pc":14,"name": "Sin Fin",                    "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": ""},
    {"pc":15,"name": "Angel Electrico",            "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": ""},
    {"pc":16,"name": "SADTF2",                     "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": ""},
    {"pc":17,"name": "FOMO slow",                  "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": ""},
    {"pc":18,"name": "Si un día te vas",           "samples": "SiUnDiaTeVas", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "FF5500"},
    {"pc":19,"name": "El Ansia",                   "samples": "ElAnsia", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "FF5500"},
];

const all_songs = [
    {"pc":0, "name": "Clone",                      "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "220099"},
    {"pc":1, "name": "Si algun día todo falla",    "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "FF0000"},
    {"pc":2, "name": "One with the machine",       "samples": "none", "audience_goggles": true, "audience_tubes": false, "show": true, "baseColor": "00FFFF"},
    {"pc":3, "name": "Lullaby",                    "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "FF7700"},
    {"pc":4, "name": "Bad boy",                    "samples": "BadBoy", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor" : "FF0000"},
    {"pc":5, "name": "FOMO",                       "samples": "none", "audience_goggles": true, "audience_tubes": false, "show": true, "baseColor": "8800FF"},
    {"pc":6, "name": "Tantra",                     "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "00FFFF"},
    {"pc":7, "name": "Sex tape",                   "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "4600FF"},
    {"pc":8, "name": "One night",                  "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": "FF0000"},
    {"pc":9, "name": "This body",                  "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": "FF00FF"},
    {"pc":10,"name": "Lockdown",                   "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "00FF00"},
    {"pc":11,"name": "No place for us",            "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "FF5500"},
    {"pc":12,"name": "Never let me down",          "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "0000FF"},
    {"pc":13,"name": "The place you'll never see", "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": ""},
    {"pc":14,"name": "Sin Fin",                    "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": ""},
    {"pc":15,"name": "Angel Electrico",            "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": ""},
    {"pc":16,"name": "SADTF2",                     "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": ""},
    {"pc":17,"name": "FOMO slow",                  "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "baseColor": ""},
    {"pc":18,"name": "Si un día te vas",           "samples": "SiUnDiaTeVasfalse", "audience_goggles": true, "audience_tubes": true, "show": true, "baseColor": "FF5500"},
    {"pc":19,"name": "El Ansia",                   "samples": "ElAnsia", "audience_goggles": false, "audience_tubes": false, "show": true, "baseColor": "FF5500"},
];