const playlist = [
    {"pc":0, "name": "Clone",                      "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "pulsating", "color1": "220099", "color2": "220099"},
    {"pc":1, "name": "Si algun día todo falla",    "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "drums", "color1": "FF0000", "color2": "000000"},
    {"pc":2, "name": "One with the machine",       "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "drums", "color1": "00FF00", "color2": "00FFFF"},
    {"pc":3, "name": "Lullaby",                    "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "drums", "color1": "FF7700", "color2": "FF1100"},
    {"pc":4, "name": "Bad boy",                  "samples": "BadBoy", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "drums", "color1": "FF0000", "color2": "FF0000"},
    {"pc":5, "name": "FOMO",                       "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "drums", "color1": "8800FF", "color2": "8800FF"},
    {"pc":6, "name": "Tantra",                     "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "pulsatingRotating", "color1": "00FFFF", "color2": "00FFFF"},
    {"pc":7, "name": "Sex tape",                   "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "drums", "color1": "000000", "color2": "4600FF"},
    {"pc":8, "name": "One night",                 "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "anim": "drums", "color1": "FF0000", "color2": "FF0000"},
    {"pc":9, "name": "This body",                  "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "alternatingColors", "color1": "FF00FF", "color2": "FF00FF"},
    {"pc":10,"name": "Lockdown",                   "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "drums", "color1": "0000FF", "color2": "0000FF"},
    {"pc":11,"name": "No place for us",            "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "pulsating", "color1": "FF5500", "color2": "FF5500"},
    {"pc":12,"name": "Never let me down",          "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "drums", "color1": "0000FF", "color2": "0000FF"},
    {"pc":13,"name": "The place you'll never see","samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "anim": "drums", "color1": ""},
    {"pc":14,"name": "Sin Fin",                   "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "anim": "drums", "color1": ""},
    {"pc":15,"name": "Angel Electrico",           "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "anim": "drums", "color1": ""},
    {"pc":16,"name": "SADTF2",                    "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "anim": "drums", "color1": ""},
    {"pc":17,"name": "FOMO slow",                 "samples": "none", "audience_goggles": false, "audience_tubes": false, "show": false, "anim": "drums", "color1": ""},
    {"pc":18,"name": "Si un día te vas",   "samples": "SiUnDiaTeVas", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "drums", "color1": "FF5500", "color2": "FF5500"},
    {"pc":19,"name": "El Ansia",                "samples": "ElAnsia", "audience_goggles": false, "audience_tubes": false, "show": true, "anim": "drums", "color1": "33FF00", "color2": "000000"},
];
